/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import controlador.GestionCliente;
import controlador.GestionFactura;
import controlador.GestionProducto;
import controlador.Pool;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;
import modelo.Cliente;
import modelo.Producto;

/**
 *
 * @author lucas
 */
public class Practica_App extends javax.swing.JFrame {
    float total;
    DefaultComboBoxModel<Cliente> cmbBoxModelC = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<Producto> cmbBoxModelP = new DefaultComboBoxModel<>();
    private DefaultTableModel model_Productos = new DefaultTableModel();
    private DefaultTableModel model_ProductosFacturar = new DefaultTableModel();
    private DefaultTableModel model_FactCliente = new DefaultTableModel();
    
    
    public Practica_App() {
        try {
            Pool.IniciaPool();
            initComponents();
            //Cargar combos
            cmbCliente.setModel(cmbBoxModelC);
            cmbProductoFact.setModel(cmbBoxModelP);
            GestionProducto.cargarCombo(cmbProductoFact);
            GestionCliente.cargarCombo(cmbCliente);
            
            //Declaración y carga de tablas modelo:
            model_Productos = (DefaultTableModel) tbl_Productos.getModel();
            model_Productos.setRowCount(0);
            GestionProducto.cargarTablaProducto(model_Productos);
            model_ProductosFacturar = (DefaultTableModel) tblFacturacionProd.getModel();
            model_ProductosFacturar.setRowCount(0);        
            model_FactCliente = (DefaultTableModel) tblFact_Cliente.getModel();
            model_FactCliente.setRowCount(0);
            
            //Longitud máxima de cuadros de texto:
            txtIdCliente.setDocument(new LimiteLongitudJTextField(10));
            txtAñadir_IDProd.setDocument(new LimiteLongitudJTextField(6));
            txtAñadir_NombProd.setDocument(new LimiteLongitudJTextField(25));
            txtCategoriaP.setDocument(new LimiteLongitudJTextField(10));
            
        } catch (SQLException ex) {
            Logger.getLogger(Practica_App.class.getName()).log(Level.SEVERE, null, ex);
        } finally{
            Pool.Cerrar();
        }
        
    }
    private boolean isNumero(KeyEvent evt) {
        // Comprobar si la pulsacion de teclado pasada
        // en evt es un número
        char caracter = evt.getKeyChar();
        return !(((caracter < '0' || caracter > '9')
                && (caracter != KeyEvent.VK_BACK_SPACE))
                || (evt.isAltDown()
                || evt.isAltGraphDown()
                || evt.isControlDown()
                || evt.isMetaDown()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelFacturar = new javax.swing.JPanel();
        lblNFactura = new javax.swing.JLabel();
        lbl_IDClienteFact = new javax.swing.JLabel();
        txtN_Factura = new javax.swing.JTextField();
        txtIdCliente = new javax.swing.JTextField();
        lblFechaFact = new javax.swing.JLabel();
        lbl_IVAFact = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        lbl_IDEmpleadoFact = new javax.swing.JLabel();
        txtEmpleado = new javax.swing.JTextField();
        lblCobradaFact = new javax.swing.JLabel();
        chbCobrada = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFacturacionProd = new javax.swing.JTable();
        lblTotalFact = new javax.swing.JLabel();
        btnFacturar = new javax.swing.JButton();
        lblProductoFact = new javax.swing.JLabel();
        cmbProductoFact = new javax.swing.JComboBox<>();
        btnAñadirProdFact = new javax.swing.JButton();
        btnBorrarProdFact = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbl_Total = new javax.swing.JLabel();
        lbl_StockFact = new javax.swing.JLabel();
        txtStockFact = new javax.swing.JTextField();
        cmb_IVA_Fact = new javax.swing.JComboBox<>();
        panelProductos = new javax.swing.JPanel();
        lbl_IDProd = new javax.swing.JLabel();
        txtAñadir_IDProd = new javax.swing.JTextField();
        txtAñadir_NombProd = new javax.swing.JTextField();
        lblNombreProd = new javax.swing.JLabel();
        lblStockProd = new javax.swing.JLabel();
        txt_AñadirStock = new javax.swing.JTextField();
        lblPrecioProd = new javax.swing.JLabel();
        txt_AñadirPrecio = new javax.swing.JTextField();
        lblCategoriaProd = new javax.swing.JLabel();
        lbl_IVAProd = new javax.swing.JLabel();
        btnAñadir = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_Productos = new javax.swing.JTable();
        btnModificarProd = new javax.swing.JButton();
        txtCategoriaP = new javax.swing.JTextField();
        cmb_IVAProd = new javax.swing.JComboBox<>();
        btnBorrarProd = new javax.swing.JButton();
        btnRestablecerTBLProd = new javax.swing.JButton();
        panelFacturas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbCliente = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFact_Cliente = new javax.swing.JTable();
        btn_EstadoCobro = new javax.swing.JButton();
        panelBorrarCliente = new javax.swing.JPanel();
        panelConsultas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNFactura.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNFactura.setText("Nº Factura:");

        lbl_IDClienteFact.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_IDClienteFact.setText("ID Cliente:");

        lblFechaFact.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFechaFact.setText("Fecha:");

        lbl_IVAFact.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_IVAFact.setText("IVA:");

        lbl_IDEmpleadoFact.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_IDEmpleadoFact.setText("ID Empleado:");

        lblCobradaFact.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCobradaFact.setText("Cobrada:");

        chbCobrada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tblFacturacionProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFacturacionProd);

        lblTotalFact.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotalFact.setText("Total:");

        btnFacturar.setText("Facturar");

        lblProductoFact.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblProductoFact.setText("Producto:");

        cmbProductoFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProductoFactActionPerformed(evt);
            }
        });

        btnAñadirProdFact.setText("Añadir producto");
        btnAñadirProdFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirProdFactActionPerformed(evt);
            }
        });

        btnBorrarProdFact.setText("Borrar seleccionado");
        btnBorrarProdFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarProdFactActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_Total.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_Total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Total.setText("0€");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Total, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lbl_Total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_StockFact.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_StockFact.setText("Stock:");

        txtStockFact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStockFactKeyTyped(evt);
            }
        });

        cmb_IVA_Fact.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "21", "10", "4" }));

        javax.swing.GroupLayout panelFacturarLayout = new javax.swing.GroupLayout(panelFacturar);
        panelFacturar.setLayout(panelFacturarLayout);
        panelFacturarLayout.setHorizontalGroup(
            panelFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFacturarLayout.createSequentialGroup()
                .addGroup(panelFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelFacturarLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotalFact, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnFacturar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFacturarLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(panelFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(panelFacturarLayout.createSequentialGroup()
                                .addGroup(panelFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblProductoFact, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNFactura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_IDClienteFact, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtN_Factura)
                                    .addComponent(txtIdCliente)
                                    .addComponent(cmbProductoFact, 0, 128, Short.MAX_VALUE))
                                .addGroup(panelFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelFacturarLayout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addGroup(panelFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblFechaFact, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_IVAFact, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(panelFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelFacturarLayout.createSequentialGroup()
                                                .addComponent(txtFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                                .addGap(57, 57, 57))
                                            .addGroup(panelFacturarLayout.createSequentialGroup()
                                                .addComponent(cmb_IVA_Fact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(panelFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(panelFacturarLayout.createSequentialGroup()
                                                .addComponent(lblCobradaFact, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(chbCobrada, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(lbl_IDEmpleadoFact, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)
                                        .addComponent(txtEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                                    .addGroup(panelFacturarLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(lbl_StockFact)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtStockFact)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnAñadirProdFact, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21)
                                        .addComponent(btnBorrarProdFact, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)))))))
                .addGap(64, 64, 64))
        );
        panelFacturarLayout.setVerticalGroup(
            panelFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFacturarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNFactura)
                    .addComponent(txtN_Factura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaFact)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_IDEmpleadoFact)
                    .addComponent(txtEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chbCobrada, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_IDClienteFact)
                        .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_IVAFact)
                        .addComponent(lblCobradaFact)
                        .addComponent(cmb_IVA_Fact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFacturarLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblProductoFact)
                            .addComponent(cmbProductoFact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBorrarProdFact)
                            .addComponent(lbl_StockFact)
                            .addComponent(txtStockFact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAñadirProdFact))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(panelFacturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFacturar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelFacturarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotalFact, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );

        jTabbedPane1.addTab("Facturar", panelFacturar);

        lbl_IDProd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_IDProd.setText("ID Producto:");

        lblNombreProd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombreProd.setText("Nombre:");

        lblStockProd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStockProd.setText("Stock:");

        txt_AñadirStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_AñadirStockKeyTyped(evt);
            }
        });

        lblPrecioProd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPrecioProd.setText("Precio:");

        txt_AñadirPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_AñadirPrecioKeyTyped(evt);
            }
        });

        lblCategoriaProd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCategoriaProd.setText("Categoría:");

        lbl_IVAProd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_IVAProd.setText("IVA:");

        btnAñadir.setText("Insertar");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });

        tbl_Productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID_Producto", "Nombre", "Stock", "Precio", "Categoria", "IVA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbl_Productos);

        btnModificarProd.setText("Confirmar modificaciones");
        btnModificarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarProdActionPerformed(evt);
            }
        });

        cmb_IVAProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "21", "10", "4" }));

        btnBorrarProd.setText("Borrar seleccionado");
        btnBorrarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarProdActionPerformed(evt);
            }
        });

        btnRestablecerTBLProd.setText("Restablecer tabla");
        btnRestablecerTBLProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestablecerTBLProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProductosLayout = new javax.swing.GroupLayout(panelProductos);
        panelProductos.setLayout(panelProductosLayout);
        panelProductosLayout.setHorizontalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelProductosLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelProductosLayout.createSequentialGroup()
                                .addComponent(btnBorrarProd, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                .addGap(181, 181, 181)
                                .addComponent(btnRestablecerTBLProd, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnModificarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelProductosLayout.createSequentialGroup()
                                .addComponent(lblPrecioProd, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_AñadirPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                .addGap(27, 27, 27)
                                .addComponent(lblCategoriaProd, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCategoriaP, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_IVAProd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(150, 150, 150)
                                .addComponent(btnAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)))
                        .addGap(25, 25, 25))
                    .addGroup(panelProductosLayout.createSequentialGroup()
                        .addComponent(lbl_IDProd, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAñadir_IDProd)
                        .addGap(18, 18, 18)
                        .addComponent(lblNombreProd, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAñadir_NombProd)
                        .addGap(18, 18, 18)
                        .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelProductosLayout.createSequentialGroup()
                                .addComponent(cmb_IVAProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelProductosLayout.createSequentialGroup()
                                .addComponent(lblStockProd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_AñadirStock)
                                .addGap(171, 171, 171))))))
        );
        panelProductosLayout.setVerticalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_IDProd)
                    .addComponent(txtAñadir_IDProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAñadir_NombProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreProd)
                    .addComponent(lblStockProd)
                    .addComponent(txt_AñadirStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioProd)
                    .addComponent(txt_AñadirPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategoriaProd)
                    .addComponent(lbl_IVAProd)
                    .addComponent(btnAñadir)
                    .addComponent(txtCategoriaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_IVAProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificarProd)
                    .addComponent(btnBorrarProd)
                    .addComponent(btnRestablecerTBLProd))
                .addGap(37, 37, 37))
        );

        jTabbedPane1.addTab("Productos", panelProductos);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("ID Cliente:");

        cmbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClienteActionPerformed(evt);
            }
        });

        tblFact_Cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Num_Factura", "Nombre", "Apellido", "Fecha", "Importe", "Estado de cobro"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblFact_Cliente);

        btn_EstadoCobro.setText("Establecer cobrada");
        btn_EstadoCobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EstadoCobroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFacturasLayout = new javax.swing.GroupLayout(panelFacturas);
        panelFacturas.setLayout(panelFacturasLayout);
        panelFacturasLayout.setHorizontalGroup(
            panelFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFacturasLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panelFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFacturasLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbCliente, 0, 138, Short.MAX_VALUE)
                        .addGap(300, 300, 300)
                        .addComponent(btn_EstadoCobro, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addGap(46, 46, 46))
        );
        panelFacturasLayout.setVerticalGroup(
            panelFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFacturasLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_EstadoCobro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2)
                .addGap(51, 51, 51))
        );

        jTabbedPane1.addTab("Facturas de Clientes", panelFacturas);

        javax.swing.GroupLayout panelBorrarClienteLayout = new javax.swing.GroupLayout(panelBorrarCliente);
        panelBorrarCliente.setLayout(panelBorrarClienteLayout);
        panelBorrarClienteLayout.setHorizontalGroup(
            panelBorrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 752, Short.MAX_VALUE)
        );
        panelBorrarClienteLayout.setVerticalGroup(
            panelBorrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Borrar Cliente", panelBorrarCliente);

        javax.swing.GroupLayout panelConsultasLayout = new javax.swing.GroupLayout(panelConsultas);
        panelConsultas.setLayout(panelConsultasLayout);
        panelConsultasLayout.setHorizontalGroup(
            panelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 752, Short.MAX_VALUE)
        );
        panelConsultasLayout.setVerticalGroup(
            panelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Consultas", panelConsultas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbProductoFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductoFactActionPerformed
              
    }//GEN-LAST:event_cmbProductoFactActionPerformed

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        Savepoint save = null;
        try {           
            save = Pool.getCurrentConexion().setSavepoint();
            Boolean existe = false;
            //Comprobación de si el producto a añadir tiene id y nombre únicos:
            for(int i=0;i<model_Productos.getRowCount();i++){
                if(txtAñadir_IDProd.getText().trim().equals(model_Productos.getValueAt(i, 0)) || txtAñadir_NombProd.getText().trim().equals(model_Productos.getValueAt(i, 1))){
                    existe = true;
                }
            }
            if(existe == true){
                JOptionPane.showMessageDialog(this, "El ID/Nombre del producto ya existen");
            }
            else{
                try {
                    GestionProducto.CargarFilaProducto(model_Productos, txtAñadir_IDProd.getText().trim(), txtAñadir_NombProd.getText().trim(),
                    Integer.parseInt(txt_AñadirStock.getText().trim()), Float.parseFloat(txt_AñadirPrecio.getText().trim()),
                    txtCategoriaP.getText().trim(), Float.parseFloat(cmb_IVAProd.getSelectedItem().toString()));
                    GestionProducto.InsertarProductoBD(model_Productos);                   
                    Pool.getCurrentConexion().commit();
                    JOptionPane.showMessageDialog(this, "Producto añadido satisfactoriamente");
                } catch (SQLException ex) {
                    try {
                        Pool.getCurrentConexion().rollback(save);
                        Logger.getLogger(Practica_App.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (SQLException ex1) {
                        Logger.getLogger(Practica_App.class.getName()).log(Level.SEVERE, null, ex1);
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Practica_App.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void btnAñadirProdFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirProdFactActionPerformed
        try {
            if(GestionProducto.ComprobarNombreTBL(model_ProductosFacturar,cmbProductoFact.getSelectedItem().toString(),Integer.parseInt(txtStockFact.getText().trim())) == false){
                GestionProducto.CargarFilaFacturaProd(model_ProductosFacturar, cmbProductoFact.getSelectedItem().toString(),Integer.parseInt(txtStockFact.getText().trim()));
                for(int i=0;i<model_ProductosFacturar.getRowCount();i++){  
                    total+=(float)model_ProductosFacturar.getValueAt(i, 2);
                    lbl_Total.setText(total+"");
                }                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Practica_App.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAñadirProdFactActionPerformed

    private void cmbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClienteActionPerformed
        try {
            GestionCliente.CargarFilaFacturaCliente(model_FactCliente, cmbCliente.getSelectedItem().toString());
        } catch (SQLException ex) {
            Logger.getLogger(Practica_App.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbClienteActionPerformed

    private void txtStockFactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockFactKeyTyped
        if (!isNumero(evt)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtStockFactKeyTyped

    private void txt_AñadirPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_AñadirPrecioKeyTyped
        if (!isNumero(evt)) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_AñadirPrecioKeyTyped

    private void txt_AñadirStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_AñadirStockKeyTyped
        if (!isNumero(evt)) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_AñadirStockKeyTyped

    private void btnBorrarProdFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarProdFactActionPerformed
        
        if(model_ProductosFacturar.getRowCount()>=0 ){
            try{
                float precioB = (float) model_ProductosFacturar.getValueAt(tblFacturacionProd.getSelectedRow(), 2);
                float total = Float.parseFloat(lbl_Total.getText().trim())-precioB;
                lbl_Total.setText(total+"");
                model_ProductosFacturar.removeRow(tblFacturacionProd.getSelectedRow());
                }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, "Añade un producto a la tabla o selecciona una fila para borrar");
            }}
    }//GEN-LAST:event_btnBorrarProdFactActionPerformed

    private void btnBorrarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarProdActionPerformed
        if(model_Productos.getRowCount()>0){
            Savepoint save = null;            
            try{
                save = Pool.getCurrentConexion().setSavepoint();
                if(GestionProducto.ComprobacionProducto((String)model_Productos.getValueAt(tbl_Productos.getSelectedRow(), 0)) == true){
                    JOptionPane.showMessageDialog(this, "El Producto no puede ser borrado debido a que pertenece a una factura");
                }
                else{           
                    GestionProducto.BorrarProductoBD(model_Productos, tbl_Productos.getSelectedRow());
                    model_Productos.removeRow(tbl_Productos.getSelectedRow());
                    Pool.getCurrentConexion().commit();
                    JOptionPane.showMessageDialog(this, "Producto borrado satisfactoriamente");
                }
            }
            catch(Exception e){
                try {
                    JOptionPane.showMessageDialog(this, "Selecciona una tabla para borrar ");
                    Pool.getCurrentConexion().rollback(save);
                    Logger.getLogger(Practica_App.class.getName()).log(Level.SEVERE, null, e);
                } catch (SQLException ex) {
                    Logger.getLogger(Practica_App.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnBorrarProdActionPerformed

    private void btn_EstadoCobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EstadoCobroActionPerformed
        Savepoint save = null;
        try{
            save = Pool.getCurrentConexion().setSavepoint();
            if((boolean)model_FactCliente.getValueAt(tblFact_Cliente.getSelectedRow(), 5) == false){
                model_FactCliente.setValueAt(true, tblFact_Cliente.getSelectedRow(), 5);   
                GestionFactura.ActualizarCobro((String)model_FactCliente.getValueAt(tblFact_Cliente.getSelectedRow(), 0));
                Pool.getCurrentConexion().commit();
            }
            else{
                JOptionPane.showMessageDialog(this, "La factura ya está cobrada");              
            }
        }
        catch(Exception e){
            try {
                JOptionPane.showMessageDialog(this, "Selecciona una fila para confirmar cobro");
                Pool.getCurrentConexion().rollback(save);
            } catch (SQLException ex) {
                Logger.getLogger(Practica_App.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_EstadoCobroActionPerformed

    private void btnModificarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarProdActionPerformed
        Savepoint save = null;
        try {
            save = Pool.getCurrentConexion().setSavepoint();
            GestionProducto.ModificarTablaProductos(model_Productos);
            Pool.getCurrentConexion().commit();
        } catch (SQLException ex) {
            try {
                Pool.getCurrentConexion().rollback(save);
                JOptionPane.showMessageDialog(this, "Error en la modificación/borrado/inserción de los datos");
                Logger.getLogger(Practica_App.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex1) {
                Logger.getLogger(Practica_App.class.getName()).log(Level.SEVERE, null, ex1);
            }
        }
    }//GEN-LAST:event_btnModificarProdActionPerformed

    private void btnRestablecerTBLProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestablecerTBLProdActionPerformed
        Savepoint save = null;
        try {
            save = Pool.getCurrentConexion().setSavepoint();
            model_Productos.setRowCount(0);
            GestionProducto.cargarTablaProducto(model_Productos);
        } catch (SQLException ex) {
            try {
                Pool.getCurrentConexion().rollback(save);
                Logger.getLogger(Practica_App.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex1) {
                Logger.getLogger(Practica_App.class.getName()).log(Level.SEVERE, null, ex1);
            }
        }
    }//GEN-LAST:event_btnRestablecerTBLProdActionPerformed


    
    public class LimiteLongitudJTextField extends PlainDocument {

        //Método para establecer longitud de texto indicada
        private int longitud;

        public LimiteLongitudJTextField(int longitud) {
            super();
            this.longitud = longitud;
        }

        @Override
        public void insertString(int offset, String str, AttributeSet attr) throws BadLocationException {
            if (str == null) {
                return;
            }
            if ((getLength() + str.length()) <= longitud) {
                super.insertString(offset, str, attr);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Practica_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Practica_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Practica_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Practica_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Practica_App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnAñadirProdFact;
    private javax.swing.JButton btnBorrarProd;
    private javax.swing.JButton btnBorrarProdFact;
    private javax.swing.JButton btnFacturar;
    private javax.swing.JButton btnModificarProd;
    private javax.swing.JButton btnRestablecerTBLProd;
    private javax.swing.JButton btn_EstadoCobro;
    private javax.swing.JCheckBox chbCobrada;
    private javax.swing.JComboBox<Cliente> cmbCliente;
    private javax.swing.JComboBox<Producto> cmbProductoFact;
    private javax.swing.JComboBox<String> cmb_IVAProd;
    private javax.swing.JComboBox<String> cmb_IVA_Fact;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCategoriaProd;
    private javax.swing.JLabel lblCobradaFact;
    private javax.swing.JLabel lblFechaFact;
    private javax.swing.JLabel lblNFactura;
    private javax.swing.JLabel lblNombreProd;
    private javax.swing.JLabel lblPrecioProd;
    private javax.swing.JLabel lblProductoFact;
    private javax.swing.JLabel lblStockProd;
    private javax.swing.JLabel lblTotalFact;
    private javax.swing.JLabel lbl_IDClienteFact;
    private javax.swing.JLabel lbl_IDEmpleadoFact;
    private javax.swing.JLabel lbl_IDProd;
    private javax.swing.JLabel lbl_IVAFact;
    private javax.swing.JLabel lbl_IVAProd;
    private javax.swing.JLabel lbl_StockFact;
    private javax.swing.JLabel lbl_Total;
    private javax.swing.JPanel panelBorrarCliente;
    private javax.swing.JPanel panelConsultas;
    private javax.swing.JPanel panelFacturar;
    private javax.swing.JPanel panelFacturas;
    private javax.swing.JPanel panelProductos;
    private javax.swing.JTable tblFact_Cliente;
    private javax.swing.JTable tblFacturacionProd;
    private javax.swing.JTable tbl_Productos;
    private javax.swing.JTextField txtAñadir_IDProd;
    private javax.swing.JTextField txtAñadir_NombProd;
    private javax.swing.JTextField txtCategoriaP;
    private javax.swing.JTextField txtEmpleado;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtN_Factura;
    private javax.swing.JTextField txtStockFact;
    private javax.swing.JTextField txt_AñadirPrecio;
    private javax.swing.JTextField txt_AñadirStock;
    // End of variables declaration//GEN-END:variables
}
